# Generated by Django 5.2.8 on 2025-12-16 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0005_alter_leaverequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['enrollment_number'], 'permissions': [('can_toggle_status', 'Can toggle gate IN/OUT'), ('can_approve_leave', 'Can approve leave requests')]},
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='approved_at',
            new_name='supervisor_approved_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='movementlog',
            name='photo',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='supervisor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warden_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='warden_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='warden_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
