# Generated by Django 5.2.8 on 2025-12-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0006_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
