# Generated by Django 5.2.8 on 2025-12-20 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0007_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementlog',
            name='linked_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gate.leaverequest'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='request_type',
            field=models.CharField(choices=[('OUTPASS', 'Day Outpass (Short Duration)'), ('LEAVE', 'Leave (Overnight/Extended)')], default='OUTPASS', max_length=10),
        ),
    ]
