# Generated by Django 5.2.8 on 2025-12-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0008_movementlog_linked_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementlog',
            name='linked_request',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='request_type',
            field=models.CharField(choices=[('Outpass', 'Outpass'), ('Leave', 'Leave')], max_length=10),
        ),
    ]
